services:
  account-db:
    image: postgres:16
    container_name: payforge-account-db
    environment:
      POSTGRES_DB: accountdb
      POSTGRES_USER: payforgeaccount
      POSTGRES_PASSWORD: accountservice
    ports:
      - "5432:5432"
    volumes:
      - account-db-data:/var/lib/postgresql/data

  ledger-db:
    image: postgres:16
    container_name: payforge-ledger-db
    environment:
      POSTGRES_DB: ledgerdb
      POSTGRES_USER: payforgeledger
      POSTGRES_PASSWORD: ledgerservice
    ports:
      - "5433:5432"
    volumes:
      - ledger-db-data:/var/lib/postgresql/data

volumes:
  account-db-data:
  ledger-db-data: